# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5096dfcf0458cd1cf39f36178617522573fe5bb5cae13b84ece76e5880b4dff834dfcfa8c8ceff131c749ad75b89c724265f941b63b923d3ec5ebe8a12324385

test:
  secret_key_base: 4e2255285b2b8e8e0925928337bada603987e8882a4b0eca4a9785dcf64663986e92da06df7ca440bf842de63bf9aef23db6df35d48c358ff200bf62dfe313d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
